# -*- coding: utf-8 -*-
"""1_vietnam_stock_vnstock3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb

<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Mục lục

# I. Cài đặt

## Cài đặt thư viện
"""

!pip install -U vnstock

"""1. Chứng khoán Việt Nam [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb)
2. Chứng khoán quốc tế: Forex, Crypto, Chỉ số [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb)
3. Dữ liệu Thị trường, hàng hoá [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/3_commodities_vnstock3.ipynb)
4. Biểu diễn dữ liệu trực quan từ Vnstock3 [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/5_visualization_data_exploration_vnstock3.ipynb)

## Nạp thư viện lần đầu

> Bạn có thể nạp toàn bộ các module của thư viện vào môi trường làm việc nếu chưa biết rõ mình cần gì hoặc chọn từng module riêng biệt để nạp vào khi đã quen thuộc.
"""

## Nạp Wrapper làm việc chính (UI chính của thư viện)
from vnstock import Vnstock

## Có thể gọi các class chi tiết trong thư viện thay vì sử dụng cấp cao nhất là Vnstock
from vnstock import Listing, Quote, Company, Finance, Trading, Screener

## Bạn cũng có thể gọi các class trong theo vị trí chi tiết của nguồn dữ liệu
from vnstock.explorer.vci import Listing, Quote, Company, Finance, Trading

# hoặc

from vnstock.explorer.tcbs import Quote, Company, Finance, Trading, Screener

"""# II. Truy xuất dữ liệu - CK Việt Nam

* Khởi tạo đối tượng stock để dùng cho tất cả thao tác truy xuất dữ liệu chứng khoán về sau. Luồng công việc minh hoạ dưới đây giả định bạn bắt đầu với 1 mã chứng khoán cần phân tích, mặc định là VN30F1M. Bạn có thể thay đổi sang mã bất kỳ bằng cách nhập tham số `symbol` tại hàm chức năng thay vì khởi tạo lại đối tượng. Ví dụ, mã `VN30F1M` được gán khi tạo đối tượng, nhưng khi gọi dữ liệu giá lịch sử, bạn có thể cập nhật mã mới là `ACB` thay vì khởi tạo lại đối tượng một cách bất tiện: `stock.quote.history(symbol='ACB', start='2020-01-01', end='2024-12-31')`

* Chọn nguồn dữ liệu thuộc danh sách được hỗ trợ: VCI, TCBS cho chứng khoán trong nước, MSN cho dữ liệu chứng khoán quốc tế và sàn HOSE.
"""

from vnstock import Vnstock
stock = Vnstock().stock(symbol='ACB', source='VCI')

"""## Listing: Liệt kê danh sách chứng khoán

### Danh sách tất cả mã CK niêm yết (đơn giản)
"""

# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
stock.listing.all_symbols()

"""### Liệt kê mã CP theo sàn (đầy đủ)"""

# Dữ liệu bao gồm tất cả các mã không kể đang niêm yết hay không
stock.listing.symbols_by_exchange()

"""### Liệt kê mã CP theo ngành icb"""

stock.listing.symbols_by_industries()

"""### Danh sách cổ phiếu theo nhóm"""

# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
stock.listing.symbols_by_group('VN30')

"""### Danh sách mã ngành theo mã icb"""

stock.listing.industries_icb()

"""## Quote: Giá chứng khoán

#### Giá lịch sử

##### Cổ phiếu
"""

df = stock.quote.history(start='2024-01-01', end='2025-03-19', interval='1D')
df

# Tất cả dataframe dữ liệu sẽ được gán thuộc tính tên và loại tài sản tương ứng
print(f'Mã chứng khoán: {df.name}')
print(f'Loại tài sản: {df.category}')

"""##### Hợp đồng tương lai"""

stock.quote.history(symbol='VN30F1M', start='2024-01-02', end='2025-03-19', interval='1D')

stock.quote.history(symbol='VN30F2411', start='2024-01-02', end='2025-03-19', interval='1D')

"""##### Chỉ số"""

stock.quote.history(symbol='VNINDEX', start='2024-01-02', end='2025-03-19', interval='1D')

stock.quote.history(symbol='HNXINDEX', start='2024-01-02', end='2025-03-19', interval='1D')

stock.quote.history(symbol='UPCOMINDEX', start='2024-01-02', end='2025-03-19', interval='1D')

"""##### Chứng quyền"""

stock.quote.history(symbol='CFPT2314', start='2024-01-02', end='2025-03-19', interval='1D')

"""##### Trái phiếu niêm yết"""

stock.quote.history(symbol='CII424002', start='2024-01-02', end='2025-03-19', interval='1D')

"""#### Intraday: dữ liệu khớp lệnh"""

# Dữ liệu khớp lệnh trong ngày giao dịch realtime hoặc ngày gần nhất (ngoài giờ giao dịch)
stock.quote.intraday(symbol='ACB', page_size=10_000, show_log=False)

# Bước giá và khối lượng giao dịch: realtime
stock.quote.price_depth('ACB')

"""## Trading: Giao dịch

### Bảng giá
"""

stock.trading.price_board(['ACB'])

stock.trading.price_board(['VCB','ACB','TCB','BID']).T # Bỏ .T để xoay trở lại đúng kiểu hiển thị bảng giá

"""## Company: Thông tin công ty

> Đã bổ sung nguồn dữ liệu từ VCI từ bản Vnstock3.2.0

### New - VCI
"""

# # Khởi tạo đối tượng
# from vnstock import Vnstock
# company = Vnstock().stock(symbol='ACB', source='VCI').company

# hoặc
from vnstock.explorer.vci import Company
company = Company('ACB')

"""Loại bỏ đoạn mã `.head()` để xem toàn bộ dữ liệu thay vì chỉ lấy 5 dòng đầu tiên.

#### Hồ sơ
"""

company.overview()

"""#### Cổ đông"""

company.shareholders()

"""#### Công ty con"""

company.subsidiaries()

"""#### Công ty liên kết"""

# Phương thức này không có trong nguồn TCBS
company.affiliate()

"""#### Lãnh đạo"""

company.officers(filter_by='working').head() # filter_by='all' hoặc 'working' hoặc 'resigned'

"""#### Tin tức"""

company.news().head(3)

"""#### Sự kiện"""

company.events().head(3)

"""#### Báo cáo phân tích"""

company.reports()

"""#### Tình hình tài chính"""

company.ratio_summary()

"""#### Thống kê giao dịch"""

company.trading_stats()

"""### TCBS"""

from vnstock import Vnstock

company = Vnstock().stock(symbol='VCB', source='TCBS').company

"""#### Tổng quan"""

company.overview()

"""#### Hồ sơ"""

company.profile()

"""#### Cổ đông"""

company.shareholders()

"""#### Giao dịch nội bộ"""

company.insider_deals().head(3)

"""#### Công ty con, liên kết"""

company.subsidiaries().head()

"""#### Ban lãnh đạo"""

company.officers().head()

"""#### Sự kiện"""

company.events().head()

"""#### Tin tức"""

company.news().head()

"""#### Cổ tức"""

company.dividends().head()

"""## Finance: Báo cáo tài chính"""

from vnstock import Vnstock
stock = Vnstock().stock(symbol='ACB', source='VCI')

"""### Bảng cân đối kế toán"""

stock.finance.balance_sheet(period='year', lang='vi', dropna=True)

stock.finance.balance_sheet(period='quarter', lang='en', dropna=True).head()

"""### Báo cáo lãi lỗ"""

stock.finance.income_statement(period='year', lang='vi', dropna=True).head()

stock.finance.income_statement(period='quarter', lang='en', dropna=True).head()

"""### Báo cáo lưu chuyển tiền tệ"""

stock.finance.cash_flow(period='year', dropna=True).head()

stock.finance.income_statement(period='quarter', lang='en', dropna=True).head()

"""### Chỉ số tài chính"""

stock.finance.ratio(period='year', lang='vi', dropna=True).head()

stock.finance.ratio(period='quarter', lang='en', dropna=True).head()

"""## New - Bộ lọc cổ phiếu

Hàm này chỉ tồn tại với nguồn dữ liệu TCBS
"""

# from vnstock import Screener

screener_df = stock.screener.stock(params={"exchangeName": "HOSE,HNX,UPCOM"}, limit=1700)
screener_df